In [1]:
import seaborn as sns  # For beautiful visualizations
import matplotlib.pyplot as plt  # For plotting

In [3]:
# Check if all required columns are available
import pandas as pd
print(df.columns)

NameError: name 'df' is not defined

In [4]:
from sklearn.metrics.pairwise import cosine_similarity

In [5]:
df = pd.read_csv("data/WA_Fn-UseC_-Telco-Customer-Churn.csv")
df = df.dropna()
features = ['tenure', 'MonthlyCharges', 'TotalCharges']  # or service-related ones

In [6]:
from sklearn.preprocessing import StandardScaler
scaled = StandardScaler().fit_transform(df[features])
similarity = cosine_similarity(scaled)

ValueError: could not convert string to float: ' '

In [7]:
features = ['tenure', 'MonthlyCharges', 'TotalCharges']  # Example

In [8]:
print(features)
print(df[features].head())

['tenure', 'MonthlyCharges', 'TotalCharges']
   tenure  MonthlyCharges TotalCharges
0       1           29.85        29.85
1      34           56.95       1889.5
2       2           53.85       108.15
3      45           42.30      1840.75
4       2           70.70       151.65

In [9]:
print(df.columns)

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='object')

In [10]:
print(df[features].dtypes)

tenure              int64
MonthlyCharges    float64
TotalCharges       object
dtype: object

In [11]:
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')  # convert to float
df.dropna(subset=['TotalCharges'], inplace=True)  # remove rows where conversion failed

In [12]:
print(df[['tenure', 'MonthlyCharges', 'TotalCharges']].dtypes)

tenure              int64
MonthlyCharges    float64
TotalCharges      float64
dtype: object

In [13]:
from sklearn.preprocessing import StandardScaler
from sklearn.metrics.pairwise import cosine_similarity

features = ['tenure', 'MonthlyCharges', 'TotalCharges']

scaled = StandardScaler().fit_transform(df[features])
similarity = cosine_similarity(scaled)

In [14]:
customer_id = 0  # pick a random customer
similar_customers = similarity[customer_id].argsort()[::-1][1:6]  # Top 5 similar
df.iloc[similar_customers]

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
3902,5999-LCXAO,Female,0,No,No,1,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,No,Mailed check,29.90,29.90,No
180,6317-YPKDH,Female,0,No,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,No,Bank transfer (automatic),29.95,29.95,Yes
6080,9526-BIHHD,Male,0,No,No,1,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,No,Mailed check,29.70,29.70,Yes
27,8665-UTDHZ,Male,0,Yes,Yes,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,No,Electronic check,30.20,30.20,Yes
3043,3677-IYRBF,Female,1,No,No,2,No,No phone service,DSL,No,...,Yes,No,No,No,Month-to-month,Yes,Electronic check,30.40,78.65,Yes

In [1]:
import os

# Create data folder if it doesn't exist
os.makedirs("data", exist_ok=True)

# Save cleaned dataframe
df.to_csv("data/cleaned_telco_data.csv", index=False)

NameError: name 'df' is not defined

In [2]:
import pandas as pd

df = pd.read_csv("data/cleaned_telco.csv")  # or cleaned_telco_data.csv if that's the latest
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes